openapi: 3.0.0
info:
  title: Queue API
  description: REST API для взаимодействия с Queue/Matchmaking сервисом.
  version: 1.0.0
servers:
  - url: http://localhost:8093

paths:
  /v1/queue/join:
    post:
      summary: Добавить пользователя в очередь матчмейкинга
      operationId: "joinQueue"
      tags:
        - Queue
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Пользователь успешно добавлен в очередь
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueueJoinResponseDto'
        '401':
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Пользователь уже в очереди
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /v1/queue/leave:
    post:
      summary: Удалить пользователя из очереди
      operationId: "leaveQueue"
      tags:
        - Queue
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Пользователь успешно удален из очереди
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueueLeaveResponseDto'
        '401':
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Пользователь не найден в очереди
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /v1/queue/status:
    get:
      summary: Получить статус очереди для текущего пользователя
      operationId: "getQueueStatus"
      tags:
        - Queue
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Статус очереди
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueueStatusResponseDto'
        '401':
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Пользователь не найден в очереди
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    QueueJoinResponseDto:
      type: object
      required: [ message, status ]
      properties:
        message:
          type: string
          example: "waiting"
          description: Сообщение о статусе очереди
        status:
          type: string
          enum: [WAITING, MATCHED, LEFT]
          example: "WAITING"
          description: Статус в очереди
        joinedAt:
          type: string
          format: date-time
          description: Время входа в очередь
        position:
          type: integer
          description: Позиция в очереди (если доступна)

    QueueLeaveResponseDto:
      type: object
      required: [ message ]
      properties:
        message:
          type: string
          example: "left"
          description: Сообщение о выходе из очереди

    QueueStatusResponseDto:
      type: object
      required: [ status ]
      properties:
        status:
          type: string
          enum: [WAITING, MATCHED, LEFT]
          example: "WAITING"
          description: Текущий статус в очереди
        joinedAt:
          type: string
          format: date-time
          description: Время входа в очередь
        waitingTime:
          type: integer
          description: Время ожидания в секундах
        position:
          type: integer
          description: Позиция в очереди (если доступна)

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Сообщение об ошибке
        status:
          type: integer
          description: HTTP статус код
