openapi: 3.0.0
info:
  title: Queue/Matchmaking API
  description: REST API для управления очередью игроков и матчмейкинга.
  version: 1.0.0
servers:
  - url: http://localhost:8093

paths:
  /v1/queue/join:
    post:
      summary: Вход в очередь
      operationId: joinQueue
      tags:
        - Queue
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Успешно добавлен в очередь
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueueResponse'
        '401':
          description: Не авторизован
        '409':
          description: Уже находится в очереди

  /v1/queue/leave:
    post:
      summary: Выход из очереди
      operationId: leaveQueue
      tags:
        - Queue
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Успешно покинул очередь
        '401':
          description: Не авторизован
        '404':
          description: Не найден в очереди

  /v1/queue/status:
    get:
      summary: Статус в очереди
      operationId: getQueueStatus
      tags:
        - Queue
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Статус очереди
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueueStatusResponse'
        '401':
          description: Не авторизован

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    QueueResponse:
      type: object
      properties:
        message:
          type: string
          example: "waiting"
        position:
          type: integer
          description: Позиция в очереди
          example: 1

    QueueStatusResponse:
      type: object
      properties:
        inQueue:
          type: boolean
        position:
          type: integer
        waitingTime:
          type: integer
          description: Время ожидания в секундах

