openapi: 3.0.0
info:
  title: Stats API
  description: REST API для получения статистики и истории матчей.
  version: 1.0.0
servers:
  - url: http://localhost:8095

paths:
  /v1/matches:
    get:
      summary: Получить список матчей пользователя
      operationId: getMatches
      tags:
        - Stats
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: query
          required: false
          schema:
            type: string
            format: uuid
          description: ID пользователя (если не указан, используется текущий пользователь)
        - name: from
          in: query
          required: false
          schema:
            type: string
            format: date-time
          description: Начало периода
        - name: to
          in: query
          required: false
          schema:
            type: string
            format: date-time
          description: Конец периода
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
          description: Номер страницы
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 20
          description: Размер страницы
      responses:
        '200':
          description: Список матчей
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchesPageResponse'
        '401':
          description: Не авторизован

  /v1/stats:
    get:
      summary: Получить статистику пользователя
      operationId: getStats
      tags:
        - Stats
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: query
          required: false
          schema:
            type: string
            format: uuid
          description: ID пользователя (если не указан, используется текущий пользователь)
      responses:
        '200':
          description: Статистика пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatsResponse'
        '401':
          description: Не авторизован

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    MatchResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        player1Id:
          type: string
          format: uuid
        player2Id:
          type: string
          format: uuid
        winnerId:
          type: string
          format: uuid
          nullable: true
        status:
          type: string
          enum: [waiting, in_progress, finished]
        duration:
          type: integer
          description: Длительность матча в секундах
        turnCount:
          type: integer
        createdAt:
          type: string
          format: date-time
        finishedAt:
          type: string
          format: date-time
          nullable: true

    MatchesPageResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/MatchResponse'
        total:
          type: integer
        page:
          type: integer
        size:
          type: integer

    StatsResponse:
      type: object
      properties:
        userId:
          type: string
          format: uuid
        wins:
          type: integer
        losses:
          type: integer
        draws:
          type: integer
        totalMatches:
          type: integer
        winRate:
          type: number
          format: float
          description: Процент побед (0-100)
        averageMatchDuration:
          type: integer
          description: Средняя длительность матча в секундах
        rating:
          type: integer
          nullable: true
          description: Рейтинг игрока (ELO)


